name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # 1. Проверяем исходники
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Листинг директории для диагностики
    - name: List backend-java directory
      run: ls -R backend-java

    # 3. Установка JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # 4. Сборка проекта Maven в правильной директории
    - name: Build with Maven
      working-directory: backend-java
      run: mvn -B package

    # 5. Optional: Отправка графа зависимостей для Dependabot
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

